### ISSUE TITLE
liblc3 outputs warning to stderr

### ISSUE THREAD

**Issue by skyman** [TricksterGuy/complx#108]
On line 224 of lc3_execute.cpp, there is a fprintf call to stderr that produces a warning that cannot be received programmatically on the lc3test end for parsing and output into the JSON format for my fork. This will also be a problem with the python backend since the lack of a stderr stream will make it impossible to catch this warning.

This part can be refactored so that the warning is passed parseably to the caller, and it is a good end goal to make it such that these warnings are only converted to strings at the outermost level of execution and not so far down the call tree.

**Comment by skyman** [comment]
So the good part is, the fix is easy, as implemented here:
https://github.com/skyman/complx/commit/9cac19ed248b15b19ad2a17b177277eb24adf79a

Unfortunately I think I'm unable to PR this into your repo since I also have the JSON stuff in previous commits in this same repo.

**Comment by TricksterGuy** [comment]
I don't like your solution as it conflates assembly code warnings the student made with problems with the xml file given which is a TA issue.

That is a problem that could be fixed with a better xml file.  Now as for the fixes to the xml file I would need that to comment on it.

**Comment by skyman** [comment]
The problem is that the student used JSR and RET in the basic assembly assignment, without using the Calling Convention at all. The assignment was written with the expectation that people would just use BR, and we do not want to involve subroutines. It's okay to penalize the student for JSR and RET here since we want to discourage their use outside of the calling convention, but the warning needs to be accessible.

I also made some further commits to the source that makes all error output from lc3test go onto stderr since those too broke my stdout parser.

**Comment by TricksterGuy** [comment]
Oh I see now, I had honestly thought the context was that you were making xml files for HW7.  Makes sense now, but wouldn't that have caused an Unexpected Call message in lc3test output? If not then it should.  I would think that's more reasonable than making a new warning message for it.

Also I think just having the grader banning certain additional opcodes/bitpatterns from running may also be a good idea.

**Comment by ausbin** [comment]
excuse me mr. brandon i am hw7, i take offense to this

**Comment by TricksterGuy** [comment]
The idea would be to use the "banned opcodes and stuff" for hw6, hw7 would be free reign.

I'll admit though having the "expected calls" checker thing being wrapped up into test-subr was a bad idea and should have been its own standalone thing that could be checked.

**Comment by TricksterGuy** [comment]
Yeah with the new stuff just toss in a "assertSubroutineCallsMade"  that would effectively catch anyone writing a subroutine for HW6.

Makes sense now to toss out that warning message, if they call an unknown subroutine then the name will appear in actual_subroutines with empty params.

**Comment by TricksterGuy** [comment]
python branch now merged which included removing that message.
