### ISSUE TITLE
Offer prebuilt binaries for all platforms and major linux distros

### ISSUE THREAD

**Issue by jacobzipper** [TricksterGuy/complx#119]
They were just bought by IBM, so someone should do something!

I'll probably look into this soon when less busy and more motivated. Definitely not necessary, but I just hate running things not natively.

**Comment by TricksterGuy** [comment]
How is this an issue for me?

Folks using other systems are more than welcome to submit a pull request for other linux support and there are build instructions for manual compilation all thats needed is the dependencies easily findable by cmake.

I am currently considering using a platform that makes distribution on all linux distros easy, but other than that I am not concerned with this, I will mainly be focused on debian/ubuntu based systems.

**Comment by jacobzipper** [comment]
I thought I put it as a feature request sorry. Regardless, lots of people have issues with docker and would much prefer a native solution for their system vs X forwarding/vnc from a container or  using a vm. I never meant for you to address this right away. It was just a request for someone contributing to the project to pick up if they wanted to. I figured I'd get to it eventually myself, but I guess you don't want this extra access ability?

**Comment by skyman** [comment]
@jacobzipper it's really, really easy to follow the manual compilation instructions to build and run this on any platform that's not Windows. I used to support a Mac version, it was literally two commands.

**Comment by jacobzipper** [comment]
I'll get on it when I get a chance then thanks. You just know... Gameboy thing going on right now so...

**Comment by ausbin** [comment]
wait what's the relevance of ibm? i'm confused

**Comment by acxz** [comment]
Not sure if this is the right place to post this but I'll go ahead. Don't want to clutter the issues/PRs with a bunch of AUR requests.

In any case, the AUR currently has a package that pulls from the latest release version of complx, [link](https://aur.archlinux.org/packages/complx/). I haven't done any thorough testing myself, but it does run. I know @TricksterGuy has mentioned that he is not confident enough in the package on Arch Linux, and that is totally understandable, but I just wanted to pipe in that there is release version complx package on the AUR.

There hasn't been enough testing on the AUR package, however, we can add a disclaimer next to the instructions that the package is experimental and is not supported by the developer of complx. Here is a following revision to the wiki page I spun up: https://gist.github.com/acxz/91653c67186eb9bcf366c8a2cdcb93c8. I would like for some opinions to see if this change is worthy.

**Comment by TricksterGuy** [comment]
I'm not planning on doing anything to fix this issue here.  All new development on complx is now in this repo: https://github.com/TricksterGuy/complx-tools. If anyone wants to add some sort of deployment tooling for any linux distro I welcome pull requests.
