### ISSUE TITLE
Failed with error code 1

### ISSUE THREAD

**Issue by rickmorthy** [TricksterGuy/complx#125]
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-imqFty/pyplusplus/

If you are not programming on python and your environment was not set up properly, you might catch this error. It requires a python setuptools to be installed.

pip install setuptools

**Comment by ausbin** [comment]
what are you trying to do?

**Comment by Rickmorthy** [comment]
I'm just saying that your Simulator require python setup tools. I was trying to install it, and spend a whole class to figure out that it's require this package. 
![Screenshot from 2019-03-13 11-49-03](https://user-images.githubusercontent.com/26745660/54385753-c1e68380-466d-11e9-9e79-d28da4b54d9c.png)

**Comment by TricksterGuy** [comment]
Thanks for making @ausbin  the owner of the simulator~

Anyway on a more serious note there are instructions for installing the program via apt on the [wiki](https://github.com/TricksterGuy/complx/wiki/Installing-Prebuilt-Binaries) if you don't need pylc3 support.  If you do need pylc3 instructions for installing that are in this [repo](https://github.com/zucchini/pyLC3)

**Comment by Rickmorthy** [comment]
Thank you guys. Is there any way to save project in any extension file, at least at .txt or may be in .asm?

**Comment by TricksterGuy** [comment]
What do you mean by "project"?

You don't use the simulator to write assembly code.  The simulator only runs assembly code.  Use a text editor to write your code, then load it in the simulator.
