### ISSUE TITLE
Backspace doesn't work editing single instruction

### ISSUE THREAD

**Issue by mck1117** [TricksterGuy/complx#19]
Repro steps:
1) Open Complx with any file open.
2) Double click on a NOP in the "Instruction Column"
3) Type "ADD R1," (this is how I found it, but it works for others too)
4) Observe that backspace does not delete characters.

-Matthew

**Comment by TricksterGuy** [comment]
Yeah this is going to sound like I am blowing you off, but you shouldn't be editing instructions in complx itself.

But I will legit take look at this tonight and report if I can repro it; however, this is a problem with the GUI toolkit library I use and not the program itself so there will be not much I can do on my end to fix it.

**Comment by TricksterGuy** [comment]
Ahh yep I had my laptop with me and tested it just now.  I am not able to reproduce and I am running Ubuntu 14.04

I will need more information what distro and version of that distro are you using?

**Comment by mck1117** [comment]
Yeah, I know I shouldn't be editing instructions in complx, but I noticed it so I figured I'd mention it.

I'm on Ubuntu 14.10 desktop x86_64.

**Comment by TricksterGuy** [comment]
I will try on that setup tonight if I can't reproduce it then there's nothing I can do.

**Comment by TricksterGuy** [comment]
Congrats you've found a bug.

Confirmed not working on Ubuntu 14.10 64 bit.

**Comment by TricksterGuy** [comment]
Playing with it a bit more its very slow when you hit backspace Eventually you may get this error message.

The program 'complx' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadLength (poly request too large or internal Xlib length erro'.
  (Details: serial 1667013 error_code 16 request_code 18 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

**Comment by TricksterGuy** [comment]
Please do the following things

sudo apt-get upgrade

Go in Language Support (search for it)
For Keyboard Input Method System set it to none.

This is a known issue that affects many gtk programs on 14.10, since wx on linux is built on top gtk it is also affected.

Reopen the issue if this doesn't fix it on your end, but it has stopped on my end.

Also for reporting this bug I will grant you one wish.

**Comment by mck1117** [comment]
Looks like that fixed it.  Thanks.

That one wish, hmmm.  That's a powerful thing to have a wish grantable by TheAlmightyBrandon.
