### ISSUE TITLE
Complx on OSX

### ISSUE THREAD

**Issue by BenTheElder** [TricksterGuy/complx#39]
Hey, I'm that guy from piazza, I know for class we're supposed to develop on linux, but for running it on my macbook on the go it'd be kinda handy.

Building complx on OSX just takes installing [wxMac](https://www.wxwidgets.org/docs/faq/osx/) via [homebrew](http://brew.sh/) and a tiny tweak to two of the makefiles's `LDFLAGS` (they use `-soname`, whereas clang supports `-install_name`). I think the install  directory should be different too, but I just set `PREFIX=./where/you/want/complx` on the commandline for make.

If you're interested, I'll open a PR with the changes. I understand if you don't want to add another platform, but the changes are pretty minimal.

Basically just:
`liblc3/Makefile`:
```
UNAME_S := $(shell uname -s)
ifeq ($(UNAME_S),Darwin)
	LDFLAGS := $(MASTER_CPP_FLAGS) -fPIC -Wall -shared -Wl,-install_name,$(OUTPUT) -L.
else
	LDFLAGS := $(MASTER_CPP_FLAGS) -fPIC -Wall -shared -Wl,-soname,$(OUTPUT) -L.
endif
```
`lc3plugins/Makefile`:
```
UNAME_S := $(shell uname -s)
ifeq ($(UNAME_S),Darwin)
	LDFLAGS = $(MASTER_CPP_FLAGS) -fPIC -Wall -shared -L../liblc3 -Wl,-install_name,$@
else
	LDFLAGS = $(MASTER_CPP_FLAGS) -fPIC -Wall -shared -L../liblc3 -Wl,-soname,$@
endif
```

Running smoothly so far:
<img width="1920" alt="screen shot 2015-09-20 at 10 48 16 pm" src="https://cloud.githubusercontent.com/assets/917931/9984765/f153809e-5feb-11e5-913a-716454004896.png">

**Comment by BenTheElder** [comment]
I'd also offer to write an `install_osx.sh` or similar, it could just require homebrew and sudo like the ubuntu one requires apt-get.

**Comment by TricksterGuy** [comment]
Yeah really hesitant on accepting this.

While the libraries used (wxWidgets) are cross platform, behaviour can be still different on different wxWidgets ports AFAIK there are a lot of things wxMac does differently than wxGTK or rather I should say doesn't do. I would have to comb through the code and see if I used any functions that wxMac doesn't implement, or does differently. Also I really don't want to deal with anyone deciding to use OSX and then have people bug me about things that don't work something like this has happened before.

But yes I would like to *eventually* have this work on Mac and Windows with setup instructions for each platform; however, today I won't accept your code unless you get both the TAs and Bills approval.

**Comment by BenTheElder** [comment]
Ok. I understand. Thanks for the response.

I may talk to them about it but probably  instead I'll just keep a branch
that tracks your master with the patch on top for tinkering. I may take a
stab at some of the other issues at some point and working from Mac
natively is pretty convenient when I don't have easy access to my desktop.

I've played with it a little bit and so far it's nice, wxMac looks like it
might use native text rendering which is also _very_ nice on recent macs.

That aside if you do ever want to support Mac / Windows, cc me on the
relevant issues and I'll see what I can do, I like C++ and cross platform
OSS so.

**Comment by BenTheElder** [comment]
My branch will be here: https://github.com/BenTheElder/complx/tree/osx.
Closing for now.
