### ISSUE TITLE
Problem with font colors and themes

### ISSUE THREAD

**Issue by QuiGonSwag** [TricksterGuy/complx#41]
I have a theme for Linux which does re skin the program properly, but I am running into a problem where the labels are  the same color as be background and become unreadable. If you could add an option to change the text font or hard code the color for the background then the problem would be fixed.

Image with text labels being unreadable (nothing selected):
![Image with text labels being unreadable] (http://puu.sh/krIPM/412ac4a5a4.png)

Image with text being selected to show the labels (text fields selected):
![Image with text being selected to show the labels] (http://puu.sh/krITg/18262b0314.png)

**Comment by TricksterGuy** [comment]
What is the theme, what program are you using to reskin the themes?

**Comment by TricksterGuy** [comment]
Can you also provide a screenshot without the text being selected?

**Comment by QuiGonSwag** [comment]
I am using gnome with tweak tool to change the theme which is Ark-Dark. 
I included 2 screen shots. The first being a screenshot without the text selected, and the second being with text selected.

**Comment by TricksterGuy** [comment]
Oh I see now, I didn't see what the problem was (had thought the first image was without the theme and second one with the theme).

I will look into this when I get home (still at work).

**Comment by TricksterGuy** [comment]
I assume you set the background color to (64, 64, 64) which for some reason I decided to make labels that color.

You can change this yourself in the code.

MemoryGrid.cpp:106

**Comment by QuiGonSwag** [comment]
Awesome! Thanks for getting back to me so fast. I really appreciate it.
