### ISSUE TITLE
Why not have console in the same window?

### ISSUE THREAD

**Issue by mmccoy37** [TricksterGuy/complx#63]
feature request

Could there be an option to have the console integrated into the main window (size adjustable)? I alt tab when switching windows and having one window dedicated to output makes alt+tab much less efficient. 

http://i.imgur.com/Eqi4HEI.png

**Comment by TricksterGuy** [comment]
Issue #29 covers this

Implementing that will allow for the layout to be completely rearranged.

**Comment by TricksterGuy** [comment]
Duplicate of #29
