### ISSUE TITLE
Squished Text on High DPI

### ISSUE THREAD

**Issue by jessrosenfield** [TricksterGuy/complx#64]
This happens both in Linux with complx and in Windows with Brandonsim. Changing resolution does not help. Neither does using an external display. It only happens to stuff that's in the output, rather than menu buttons, etc. I don't know why I have this issue with both of them if Brandonsim is written in Java and Complx in C++. I expect this will become more of an issue as students use newer computers. I already know other students that have this issue.
![view of globbered text](https://cloud.githubusercontent.com/assets/1537213/13471259/d36f15ee-e07d-11e5-84b2-cf46dac407b3.png)

**Comment by jgkamat** [comment]
Have you tried changing your default fonts? Maybe linux mint has this issue because it sets the font sizes too big (it seems to be happening only on your monospace font, your other fonts look ok). If you lower your resolution and still see the issue, it probably dosen't have to do with DPI. 

This is with DejaVuMono (ttf)
![testcardata102](https://cloud.githubusercontent.com/assets/4349709/13483010/a60f898a-e0be-11e5-9232-0ee03a8b245c.png)

**Comment by jgkamat** [comment]
If you have docker installed, could you run 
`docker run -ti -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix $LINK "jgkamat/complx"`?

That should run complx in isolation w/ default ubuntu fonts on your machine. If you still see an error with those settings, its probably a bug

**Comment by jessrosenfield** [comment]
Changing monospace font/font size did not fix problem. However, setting "Text scaling factor" to 0.7 did! I'll have to play with docker later and let you know.

**Comment by jgkamat** [comment]
I think changing your scaling factor on windows should fix your windows issues as well (with logisim).

afaik I don't think it would be easy to fix this in any program individually (other than override the scaling factor, which would break other users), but I don't know too much about fonts.

**Comment by jessrosenfield** [comment]
Afraid not. The issue w/ logisim is the same on linux in my vm as it is on just windows. I tried opening it with the different font factor and it didn't make a difference.

**Comment by TricksterGuy** [comment]
Not an issue that can be fixed here.  Its a wxWidgets issue and can be fixed by compiling latest version of wx against gtk3
