### ISSUE TITLE
Homebrew Formula

### ISSUE THREAD

**Issue by skyman** [TricksterGuy/complx#73]
Hey Brandon,

I created a formula for the Homebrew package installer for macOS that installs the current version (4.15.0) of complx. It can be run on any Mac device with the following command after [installing Homebrew](https://brew.sh/):

`brew install skyman/homebrew-gt/complx`

It uses cmake and wxMac as dependencies that are downloaded through Homebrew so it shouldn't break so easily, it will just need to be updated every once in a while to reflect the new versions (or, if you can maintain a "release" branch, we can configure it to download the latest release automatically: it cant be done right now because you can specify a branch or a tag but not "the latest tag" dynamically)

Just wanted to point this out so that if you want, you can add it to the README. I can confirm that it works on macOS Sierra, but not on others yet. We can post on Piazza too to ask Mac users to test it out, perhaps in the process we will have saved some people from the whole Virtual Machine fuss.

Thanks for all your work on complx :)

**Comment by skyman** [comment]
@TricksterGuy now that I met you irl I feel like I have more of a right to pester you about this :)

**Comment by TricksterGuy** [comment]
you can submit a pull request for this.  Also updating the wiki with build instructions.  You now have the right to.

**Comment by skyman** [comment]
So it can be on my homebrew tap (repo) but that might be problematic after this semester where I might not be able to maintain it.

However, I think we're (almost) eligible for being listed on the upstream homebrew tap. I'll work on it a bit this week.

**Comment by TricksterGuy** [comment]
I can probably do this myself now since I have a "MACOS" but as it stands this repo is now no longer being worked on. All new development is here - https://github.com/TricksterGuy/complx-tools
