### ISSUE TITLE
Readd support for binary literals

### ISSUE THREAD

**Issue by skyman** [TricksterGuy/complx#82]
Complx allows assembly code to include labels that start with the hexadecimal x or the boolean b and consist entirely of numbers afterwards. However, when these labels are being evaluated for use in BR, etc. what happens is the immediate value parser takes precedence, using the immediate value as the offset instead of that of the label relative to the PC, as shown in this example:

```
.orig x3000
START       BR x0

            LEA R0, NOWORKS
            PUTS
            HALT

x0          LEA R0, WORKS
            PUTS
            HALT


WORKS	    .stringz "Works"
NOWORKS     .stringz "Doesnt work"
.end
```

The output is:
> Doesnt work

As a result, there is no possibility of using these labels for anything since their value will always be interpreted as an immediate value instead of the label offset. Therefore it might be wise to disallow the use of hexadecimal / binary numbers as labels to prevent confusion that might arise from this situation.

**Comment by TricksterGuy** [comment]
Looks to be expected behavior.

The label x0 should be rejected though

**Comment by skyman** [comment]
The same applies for b0 and maybe even #0 (havent checked, just noting)

**Comment by TricksterGuy** [comment]
Pretty certain the status of binary literals is in limbo.

There is some commented out code for parsing them.
