### ISSUE TITLE
Is there a way to entend complex to be driven by clock ?

### ISSUE THREAD

**Issue by Kiddinglife** [TricksterGuy/complx#99]

**Comment by ausbin** [comment]
what do you mean?

**Comment by Kiddinglife** [comment]
Now LC3 is istruction-based simulator but what I want is clk-based simulator.
I mean I should see states of datapath, mar, pc, state machina and so on.

**Comment by ausbin** [comment]
I guess you could make an LC-3 in a circuit simulator like https://github.com/ra4king/CircuitSim. The issue with that I'm assuming is performance?

**Comment by TricksterGuy** [comment]
This is an instruction level simulator only.  A CPU simulator is outside the scope of this repository.

**Comment by Kiddinglife** [comment]
thanks. guys.
